{"name": "Проверка отображения номера заказа в разделе \"В работе", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:192:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:510:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16", "trace": "pages = <web_pages.UIWorkerWeb object at 0x000001E3BA4F7590>\n\n    @pytest.fixture(scope='function')\n    def login(pages):\n        \"\"\" Войти в аккаунт \"\"\"\n>       pages.login()\n\nconftest.py:41: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nweb_pages\\auth_user_page.py:33: in login\n    self.set_email_field(PersonData.user_login)\nweb_pages\\auth_user_page.py:16: in set_email_field\n    self.wait_for_element_to_be_clickable(AuthLoginLocators.EMAIL_FIELD)\nweb_pages\\base_page.py:64: in wait_for_element_to_be_clickable\n    WebDriverWait(self.driver, 3).until(EC.element_to_be_clickable(locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"dec3cb6a-2d3b-4746-8ca1-86babda5a9b1\")>\nmethod = <function element_to_be_clickable.<locals>._predicate at 0x000001E3BB157F60>, message = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nE       WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:192:5\nE       NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:510:5\nE       dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n.venv\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py:105: TimeoutException"}, "description": "Получаем номер нового заказа, и проверяем, что номер заказа появился в разделе \"В работе\"", "parameters": [{"name": "driver_do", "value": "'firefox'"}], "start": 1712593757825, "stop": 1712593757825, "uuid": "5fbf2e5f-c0e1-47e5-a234-49354fecd7e2", "historyId": "7fc07f0893e73c345cbb9a1db6b6bcec", "testCaseId": "42efcf665c18715edf0856ca73d54709", "fullName": "tests.test_create_order.TestCreateOrder#test_new_order_appears_in_work_list", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "Mi-Notebook"}, {"name": "thread", "value": "13692-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}